<?php

namespace ContainerNh2zBtO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z59tJ14Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z59tJ14' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.z59tJ14'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'recipe' => ['privates', '.errored..service_locator.z59tJ14.App\\Entity\\Recipe', NULL, 'Cannot autowire service ".service_locator.z59tJ14": it needs an instance of "App\\Entity\\Recipe" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'recipe' => 'App\\Entity\\Recipe',
            'entityManager' => '?',
        ]);
    }
}
