<?php

namespace ContainerNh2zBtO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecipeControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.btwogvC.App\Controller\RecipeController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.btwogvC.App\\Controller\\RecipeController::index()'] = ($container->privates['.service_locator.btwogvC'] ?? $container->load('get_ServiceLocator_BtwogvCService'))->withContext('App\\Controller\\RecipeController::index()', $container);
    }
}
