<?php

namespace Container0qpO4gT;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I3ge05SService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i3ge05S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i3ge05S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\RecipeController::index' => ['privates', '.service_locator.btwogvC.App\\Controller\\RecipeController::index()', 'getRecipeControllerindexService', true],
            'App\\Controller\\RecipeController::myRecipes' => ['privates', '.service_locator.btwogvC.App\\Controller\\RecipeController::myRecipes()', 'getRecipeControllermyRecipesService', true],
            'App\\Controller\\RecipeController::new' => ['privates', '.service_locator..fUBbna.App\\Controller\\RecipeController::new()', 'getRecipeControllernewService', true],
            'App\\Controller\\RecipeController::show' => ['privates', '.service_locator.XJ9LaKn.App\\Controller\\RecipeController::show()', 'getRecipeControllershowService', true],
            'App\\Controller\\RecipeController::edit' => ['privates', '.service_locator.z59tJ14.App\\Controller\\RecipeController::edit()', 'getRecipeControllereditService', true],
            'App\\Controller\\RecipeController::delete' => ['privates', '.service_locator.z59tJ14.App\\Controller\\RecipeController::delete()', 'getRecipeControllerdeleteService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.g9BceMG.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\RecipeController:index' => ['privates', '.service_locator.btwogvC.App\\Controller\\RecipeController::index()', 'getRecipeControllerindexService', true],
            'App\\Controller\\RecipeController:myRecipes' => ['privates', '.service_locator.btwogvC.App\\Controller\\RecipeController::myRecipes()', 'getRecipeControllermyRecipesService', true],
            'App\\Controller\\RecipeController:new' => ['privates', '.service_locator..fUBbna.App\\Controller\\RecipeController::new()', 'getRecipeControllernewService', true],
            'App\\Controller\\RecipeController:show' => ['privates', '.service_locator.XJ9LaKn.App\\Controller\\RecipeController::show()', 'getRecipeControllershowService', true],
            'App\\Controller\\RecipeController:edit' => ['privates', '.service_locator.z59tJ14.App\\Controller\\RecipeController::edit()', 'getRecipeControllereditService', true],
            'App\\Controller\\RecipeController:delete' => ['privates', '.service_locator.z59tJ14.App\\Controller\\RecipeController::delete()', 'getRecipeControllerdeleteService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.g9BceMG.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\RecipeController::index' => '?',
            'App\\Controller\\RecipeController::myRecipes' => '?',
            'App\\Controller\\RecipeController::new' => '?',
            'App\\Controller\\RecipeController::show' => '?',
            'App\\Controller\\RecipeController::edit' => '?',
            'App\\Controller\\RecipeController::delete' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\RecipeController:index' => '?',
            'App\\Controller\\RecipeController:myRecipes' => '?',
            'App\\Controller\\RecipeController:new' => '?',
            'App\\Controller\\RecipeController:show' => '?',
            'App\\Controller\\RecipeController:edit' => '?',
            'App\\Controller\\RecipeController:delete' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);
    }
}
