<?php

namespace ContainerFAnxulb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecipeControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XJ9LaKn.App\Controller\RecipeController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XJ9LaKn.App\\Controller\\RecipeController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'recipe' => ['privates', '.errored..service_locator.XJ9LaKn.App\\Entity\\Recipe', NULL, 'Cannot autowire service ".service_locator.XJ9LaKn": it needs an instance of "App\\Entity\\Recipe" but this type has been excluded in "config/services.yaml".'],
        ], [
            'recipe' => 'App\\Entity\\Recipe',
        ]))->withContext('App\\Controller\\RecipeController::show()', $container);
    }
}
