<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0qpO4gT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0qpO4gT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0qpO4gT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0qpO4gT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0qpO4gT\App_KernelDevDebugContainer([
    'container.build_hash' => '0qpO4gT',
    'container.build_id' => '4e29d830',
    'container.build_time' => 1731347897,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container0qpO4gT');
